listeners:
- query_port: 25577
  motd: '&1Another FlameCord server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - cakmalobi
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 2022
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 17000
stats: 0559be12-d543-479f-81c2-58bc99759842
player_limit: 2022
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  cakmalobi:
    motd: '&1Just another FlameCord - Forced Host'
    address: localhost:25560
    restricted: false
  lobi:
    motd: '&1Just another FlameCord - Forced Host'
    address: localhost:25561
    restricted: false
